import React from "react";
import "./FrequentlyAskedQ.css";

const FrequentlyAskedQ = () => {
  return (
    <div className="frequentlyaskedq">
      <h1 className="title1">Returns and Exchanges:</h1>
      <ul>
        <h3>Important Information:</h3>
        <li>
          You need to securely package and send the products you wish to return
          in their original packaging, undamaged, with tags intact, and unused.
        </li>
        <li>
          When returning fragile items, you must package them with the same
          protective materials (styrofoam, bubble wrap, box) used when they were
          sent to you. Therefore, any damage occurring during shipping is the
          customer's responsibility.
        </li>
        <li>
          For the return of hygiene-sensitive items such as underwear, swimwear,
          yoga mats, cosmetics, and socks, the products must be unused and the
          protective seals and tags must not be removed.
        </li>
        <li>
          If the product does not meet the return conditions, the item will be
          shipped back to your address free of charge.
        </li>
        <li>
          If, after the return process, your cart total is below 200TL, a
          shipping fee of $11.90 will be charged to you.
        </li>
      </ul>
      <ol>
        <li className="bold">I want to return the product I purchased. What should I do?</li>
        <p>
          If you are not satisfied with any of the products you purchased, you
          can return them within 14 days and receive a refund. To initiate the
          return process, simply go to the "My Orders" page and click the
          "Create Return" button for the relevant product. With the "Yurtiçi
          Kargo return code" generated by the system, you can send your return
          back for free from any Yurtiçi Kargo branch.
        </p>
        <li className="bold">I want to exchange the products I purchased. What should I do?</li>
        <p>
          Unfortunately, direct exchanges for the products you purchased are not
          possible. However, you can use your return rights for the purchased
          product and request a gift voucher. With this voucher, you can
          purchase the desired product without making an additional payment. For
          more information, you can email info@cozycorner.com or call 0999 999
          99 99 for detailed assistance.
        </p>
        <li className="bold">The product I received is damaged/faulty. What should I do?</li>
        <p>
          If the product you purchased from cozycorner.com is damaged or faulty,
          you can return it within 30 days and receive a refund. You can open a
          request from the email info@cozycorner.com, or call 0999 999 99 99 to
          contact us and send back your package with free shipping.
        </p>
      </ol>

      <ol>
        <h3 className="title2">Orders:</h3>
        <li className="bold">What payment methods do you accept?</li>
        <p>
          At CozyCorner, we accept all major credit cards. You can also make
          payments via bank transfer. The necessary bank information for bank
          transfers is provided on the payment page.
        </p>
        <li className="bold">How secure is it to enter my credit card information?</li>
        <p>
          At CozyCorner, all necessary security measures are taken. With our
          İyzico payment infrastructure, your personal information is secure
          with SSL security and fraud prevention services.
        </p>
        <li className="bold">Do you offer gift wrapping?</li>
        <p>
          You can add a gift card and gift wrapping for orders where you have
          selected the gift message on the cart page.
        </p>
        <li className="bold">In which currency will my order be charged from my account?</li>
        <p>
          CozyCorner, offering global shipping services, supports payment in
          Turkish Lira (TL), US Dollars (USD), and Euros (EUR) based on our
          customers' preferences.
        </p>
      </ol>
    </div>
  );
};

export default FrequentlyAskedQ;
